### PR TITLE
Automated Test Suite

### PR DESCRIPTION
**Pull request by ghost**
Simple automated regression suite for the UI. Uses local Firefox driver
within a series of unit tests.

Also there's a bug where your css doesn't autowrap text. I'll be working on that and pushing that not in this merge, but the next one.

### CODE REVIEW

**Comment by cuducos** [comment]
Hi Chris, many thanks for the PR!

Sounds really good to have a test suit for the UI, however, I'd like to discuss a few points before merging it. I've never wrote any UI test, and I've never worked with Selenium before – so sorry about any newbie questions:

* First of all, is it really worth it to use the production URL in the tests? I mean, if I'm doing some changes in the code, wouldn't it be better if the test suit could help me spot an error before the code gets uploaded to the production server? Is there any best practice related to this in UI tests? Maybe we could use an environment variable and set the URL for the tests locally (`localhost:5000`, `127.0.0.1:5000` whatever)…
* Is there a way to include your tests in the `nosetests` routine? If not, can you add the instructions to run your tests to Tests section at the `README.md`?
* Would you mind avoiding spaces in the file/folder naming? Maybe rename `webdriver tests` to `tests_webdriver` or yet to `webdriver` inside the `whiskyton/tests` folder.
* Finally, what about including Selenium (and its version) to the `requirements.txt`? For me, when it comes to development it sounds a pretty good idea, but maybe you have your own reasons not to. Anyway, it would avoid the `ImportError` if someone forgets to install it manually.

Once more, thanks for your contribution. I can try to help you with the points I raised here, just let me know if what you think about them.

Cheers,

**Comment by cloverchio** [comment]
No you're right, there is no benefit to using the production URL as testing should be done on the snapshot. I left it there a placeholder for whatever localhost URL you may be using. 

However it wouldn't take me much time to just create a function that takes your local environment as an argument.

As far as implementing this with nose, I'd have to look more into it as I'm not entirely familiar with the library (more of a Java guy) but it could probably be done.

**Comment by cuducos** [comment]
Ok, Chris. I can merge this (maybe in another branch) and work on these minor details myself (before merging into the _master_). Is that ok?
Many thanks.

**Comment by cuducos** [comment]
Merged to [_ui-tests_ branch](https://github.com/cuducos/whiskyton/commits/ui-tests). I already added a few commits fixing the 4 points I raised yesterday. Feel free to take a look before I merge to _master_ .

**Pull request closed without merging**
